### ISSUE TITLE
No LED Notification Light displaying

### ISSUE THREAD

**Issue by diominandrew** [Moyster/nougat_device_meizu_m2note#10]
No LED Notification Light displaying

**Comment by Gargarospo** [comment]
My LED notifications are working fine (both with beta 2, and with beta 3)

**Comment by diominandrew** [comment]
Sorry! My LED notifications are working too now. 
Thanks Moyster, this is really great work.

**Comment by Moyster** [comment]
Well... Can't say I don't like when a bug fixes itself :')
