### ISSUE TITLE
Whatsapp videos won't play

### ISSUE THREAD

**Issue by gloddo** [Moyster/nougat_device_meizu_m2note#11]
I'm sorry to bother, I don't even consider this a major bug but I thought you'd like to know every single one happens.
When I open a video, sent or received, directly from whatsapp's chat, It won't play, saying that "gallery app has interrupted"

![image](https://cloud.githubusercontent.com/assets/19632012/23068361/9c39982c-f523-11e6-9b10-c2c1380f3a71.png)

**Comment by gloddo** [comment]
That's a huge screenshot, sorry for that lol

**Comment by franci22** [comment]
Try to use another video player, like VLC.
---
Prova ad usare un altro player come VLC :)

**Comment by gloddo** [comment]
It worked, but it's just a workaround, I think a fully working stock app would be better, also not to bloat the system with too many apps

**Comment by Moyster** [comment]
Hello,

If you can make a logcat of the moment when you open that video and it crashes, it'll be better than a screenshot ;)
I'm wondering tho, is the video crashing gallery app OR only crashing when opening FROM what'sapp ?

**Comment by gloddo** [comment]
I tried a couple apps for logcats but I couldn't do it, I'm sorry.. Anyway, I tried opening videos directly from gallery, it prompts me if I want to use default "video player" app and that makes the galley app crash.

**Comment by gloddo** [comment]
This is fixed in beta 4. Thank you
