### ISSUE TITLE
WhatsApp doesn't get messages in background

### ISSUE THREAD

**Issue by gloddo** [Moyster/nougat_device_meizu_m2note#17]
I'm on beta 5 and I gave WhatsApp all permissions (keep awake, backround etc).
This time I flashed only superSU, but I use no greenify or any battery saver/optimizer app, so I think this has to be system-side. 
The phone does enter deepsleep and battery stats show that it gets awaken sometimes, but not from WhatsApp messages

**Comment by Moyster** [comment]
Is this still happening ? I'm not sure but doesn't WhatsApp rely on a cloud messaging system ? You may want to try and install GMS using the gapps application ;)
