### ISSUE TITLE
if (dual sim && enable gps && use some navigation app): lose sim card signal

### ISSUE THREAD

**Issue by tt677666** [Moyster/nougat_device_meizu_m2note#18]
if  (dual sim card && enable gps && use some navigation app): 
       {
           sim card offline
       }

#thank for your working

[gps1.log.txt](https://github.com/Moyster/nougat_device_meizu_m2note/files/813200/gps1.log.txt)
[gps2.log.txt](https://github.com/Moyster/nougat_device_meizu_m2note/files/813202/gps2.log.txt)

**Comment by Moyster** [comment]
It might have changed, try with latest build (beta 7 "IsNoJoke")

**Comment by Moyster** [comment]
Well, if this is still happening, feel free to reopen the issue :)

**Comment by tt677666** [comment]
@Moyster  

i try it agin with version "lineage-14.1-20170430-UNOFFICIAL-m2note.zip",found  the bug still unsolved 
and i collected log with catlog hope to help you.
thx!

**Comment by Moyster** [comment]
I'll wait for wileyfox spark/spark+ update to nougat to update our GPS drivers (with Sparks blobs), it's hard for me to get 2 simcards and test.
If you need this and want to help, I guess you could try using blobs from S3plus (from MAD team, they updated gps to N already) but I'm pretty sure it won't work without android-source sided changes.

ps: wileyfox spark(+) should be updated before end of june, so... fingers crossed.

**Comment by Moyster** [comment]
It was to be expected that Wileyfox are crooks and liars, Their mediatek devices will only get updated Late July (read. they will release an update around October 2017, the very same bugged June 2017 update, just... 6 months after so they're sure their Sparks users have moved on and nobody will notice.  
Will see if N blobs from already released roms are properly working.
