### ISSUE TITLE
setup wizard crashes because of sim card or sdcard

### ISSUE THREAD

**Issue by bads-tm** [Moyster/nougat_device_meizu_m2note#20]
I don't know if this happens on other device's, but might be usefu for other people who might encounter.

Some extra info:
Model M571H
20170225 build from XDA and md5 looks are same
Lithuanian network sim card

**Comment by Moyster** [comment]
Yeah, sorry I forgot to answer that, I'm currently not that much available.

I think the **easy solution** is to flash G-apps, GoogleWizard starts correctly, I'm not the only one with that bug on a Mtk platform, hopefully someone will search/find for a fix :)

**Comment by bads-tm** [comment]
Or simply remove sim and sdcard slot, do setup and finish

**Comment by dariusworks** [comment]
note: this is me ( @bads-tm )
