### ISSUE TITLE
Beta 8, camera crash

### ISSUE THREAD

**Issue by netrias** [Moyster/nougat_device_meizu_m2note#25]
[alogcat.2017-04-02-14-55-46+0300.txt](https://github.com/Moyster/nougat_device_meizu_m2note/files/888348/alogcat.2017-04-02-14-55-46.0300.txt)
Wiped cache and dalvik cache

**Comment by Moyster** [comment]
See the hotfix here : 
https://forum.xda-developers.com/devdb/project/?id=19269#downloads

Enjoy :)
