### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by dmitrywxz** [Moyster/nougat_device_meizu_m2note#26]
Hi! there is a problem.
Collect the firmware,everything seems fine but camera is not working.the tree is yours.with the latest edits.Do I need a patch for the camera?if Yes, then tell me what.
Thanks in advance!

**Comment by franci22** [comment]
Flash this zip https://forum.xda-developers.com/attachment.php?attachmentid=4100012&d=1491250714

**Comment by dmitrywxz** [comment]
Not working!
