### ISSUE TITLE
Update audio_policy.conf; Update audio_effects.conf; Update audio_device.xml

### ISSUE THREAD

**Issue by teik-off** [Moyster/nougat_device_meizu_m2note#4]
https://github.com/dmitrywxz/LineageOS_device_meizu_m2note/commits/los-14.1

**Comment by Moyster** [comment]
Makes no sense, doing changes just to make changes is pointless.

"AUDIO_DEVICE_IN_FM"
Do you really think we have an FM INPUT on a device without FM radio ? I even removed FMradio driver from the kernel =/

**Comment by teik-off** [comment]
Only this is tested and really works. The sound is louder and cleaner!

**Comment by teik-off** [comment]
He agrees, has gone too far in FM.
But, the sound becomes better if to make so:
- sampling_rates 44100
+ sampling_rates 44100|48000

**Comment by teik-off** [comment]
He agrees, has gone too far in FM.
But, the sound becomes better if to make so:

   - sampling_rates 44100


   - sampling_rates 44100|48000


2017-02-06 15:16 GMT+03:00 Moyster <notifications@github.com>:

**Comment by Moyster** [comment]
make it a pull request please, thanks :)
