### ISSUE TITLE
camera crash after update build 14

### ISSUE THREAD

**Issue by alexfrance12** [Moyster/nougat_device_meizu_m2note#40]
hello everybody :) i was in build 13 on my meizu m2 note and everything lag and crash and freeze, and cam working, and I updated with my TWRP on build 14 (wipe cach & davilk cach) everything were fast and good, right now my rear camera crash, and only the front camera work. what's the solution ? thanks ;)

grateful for custom firmware

**Comment by Moyster** [comment]
There should be a solution in the Xda thread posted by Numpea, I'll close this issue ;)
