### ISSUE TITLE
Gran problema al intalar

### ISSUE THREAD

**Issue by javijdd** [Moyster/nougat_device_meizu_m2note#41]
![screenshot_20170604-143407](https://user-images.githubusercontent.com/29154388/26887679-1c0fc346-4b55-11e7-8989-2a19f966d332.png)
No pasa después de la conexión wifi estoe estate sucedido en vara rom desde la versión 12 no oficial ayuda

**Comment by eduardo579** [comment]
You have two methods to make it work: 

Flash Gapps just after you flash the rom

Or remove the SIM card after you flash the rom, doing the initial configuration and insert the SIM after the setup.

**Comment by javijdd** [comment]
Yes is work is not work cam cam open & close

**Comment by alexfrance12** [comment]
I've same problème with my camera ...
