### ISSUE TITLE
Camera close version 15

### ISSUE THREAD

**Issue by javijdd** [Moyster/nougat_device_meizu_m2note#43]
![screenshot_20170618-090346](https://user-images.githubusercontent.com/29154388/27263386-4306781a-5414-11e7-8acf-7b421c9c745e.png)
![screenshot_20170618-090640](https://user-images.githubusercontent.com/29154388/27263391-63174986-5414-11e7-8863-008d16350c3a.png)

**Comment by kosmosofby** [comment]
Same problem

**Comment by Moyster** [comment]
Hi there, There's a solution on the Xda thread, some people deleted a file and got camera working back, I'm not exactly sure it works (but a reliable tester tried and reported it works fine).
Deleting the "CAMERA_VERSION" file should fix it, search for that on Xda and read the comments/feedbacks and make a backup before doing anything ;)

**Comment by kostasil** [comment]
Hello guys. Where can i find this file?

**Comment by javijdd** [comment]
CAMERA_VERSION delete i camera working 100% thanks
