### ISSUE TITLE
Data Manager don't work

### ISSUE THREAD

**Issue by ErenTitan** [Moyster/nougat_device_meizu_m2note#44]
When I try to open the data manager the app close automatically and I can't see my data.

**Comment by ErenTitan** [comment]
Here is the logcat, thank you for all of your work @Moyster
[DataManager.txt](https://github.com/Moyster/nougat_device_meizu_m2note/files/1085934/DataManager.txt)

**Comment by Moyster** [comment]
Hi there,
Did you try wiping your dalvik cache ? I can't reproduce your bug here, data restriction / management works fine without FC.

**Comment by ErenTitan** [comment]
Yes now works fine thanks for the feedback you can close this issue. Thank you for reply.
