### ISSUE TITLE
Pokémon Go

### ISSUE THREAD

**Issue by ErenTitan** [Moyster/nougat_device_meizu_m2note#47]
When I open the game give me an error: GPS signal could not be detected.

**Comment by ErenTitan** [comment]
I have high precision activated.

**Comment by Moyster** [comment]
Works fine, make a backup and do a clean wipe ;)

**Comment by ErenTitan** [comment]
I did but it still gives me the same error but Google Maps works. What can I do?

**Comment by Moyster** [comment]
Try "gps test" app, if it gives you "GNSS status : 3d fix" it means gps works properly.  
Make sure you don't have root enabled / flashed mods / etc.. and reinstall Pokemon Go clean from the appstore.

**Comment by ErenTitan** [comment]
@Moyster I install android 5.1 and now works but in 7.1.2 didn't detect Gps Signal. Whan can I do?

**Comment by ErenTitan** [comment]
The gps works fine because I flash the Cyanogenmod 5.1 Rom and the game didn't give me any error. Now I put android 7.1 and I'll try to do what you told me.

**Comment by ErenTitan** [comment]
Yes!!! Now It works well thank you @Moyster!
