### ISSUE TITLE
KRACK Wi-Fi vunerability

### ISSUE THREAD

**Issue by nazar554** [Moyster/nougat_device_meizu_m2note#58]
Upstream LineageOS already has the patch (as of today)
https://review.lineageos.org/#/q/project:LineageOS/android_external_wpa_supplicant_8
https://www.krackattacks.com

**Comment by Moyster** [comment]
Hi and thanks for forwarding this, I saw the topic on lineage's gerrit.  
Don't have time this week to do a release, I'll probably do it this sunday-ish. If you "really" want to not be vulnerable, you can download any lineage-14.1 arm 64bits rom and extract its' wpa_supplicant bin, then only push that bin to m2note, I'm not rushing anything, most vendors including Google & Apple are not, so... :>
