### ISSUE TITLE
Slow charging on the build 21

### ISSUE THREAD

**Issue by aftersilence** [Moyster/nougat_device_meizu_m2note#68]
Very slow charging at the latest 21 build even using 2A original charger (compared to flyme roms its slower in 2-3 times). Using USB charging from PC its seems that its not charged at all.

**Comment by Moyster** [comment]
Didn't see anything different, are you sure your battery / usb cable is not damaged ?

**Comment by Moyster** [comment]
should be fixed in the next build :)
