### ISSUE TITLE
Instagram Crash

### ISSUE THREAD

**Issue by micheleberrettis1** [Moyster/nougat_device_meizu_m2note#70]
Logcat above of instagram crashing while playing stories

---- 17 gen 2018 12:04:19 ----

01-17 10:43:13.083   733   733 W PackageManager: Not granting permission android.permission.RECORD_AUDIO to package com.instagram.android because it was previously installed without

01-17 10:43:13.083   733   733 W PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.instagram.android because it was previously installed without

01-17 10:43:13.083   733   733 W PackageManager: Not granting permission android.permission.READ_PHONE_STATE to package com.instagram.android because it was previously installed without

01-17 10:43:13.083   733   733 W PackageManager: Not granting permission android.permission.RECEIVE_SMS to package com.instagram.android because it was previously installed without

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission .permission.C2D_MESSAGE in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission .permission.RECEIVE_ADM_MESSAGE in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission com.instagram.direct.permission.PROTECTED_DEEPLINKING in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission com.amazon.device.messaging.permission.RECEIVE in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission com.htc.launcher.permission.READ_SETTINGS in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission com.huawei.android.launcher.permission.CHANGE_BADGE in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Unknown permission android.permission.UPDATE_APP_BADGE in package com.instagram.android

01-17 10:43:13.083   733   733 W PackageManager: Not granting permission android.permission.CALL_PHONE to package com.instagram.android because it was previously installed without

01-17 10:43:13.084   733   733 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.GET_ACCOUNTS to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.CAMERA to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.READ_CONTACTS to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.ACCESS_FINE_LOCATION to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.RECORD_AUDIO to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.WRITE_EXTERNAL_STORAGE to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.READ_PHONE_STATE to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.RECEIVE_SMS to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission .permission.C2D_MESSAGE in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission .permission.RECEIVE_ADM_MESSAGE in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission com.instagram.direct.permission.PROTECTED_DEEPLINKING in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission com.amazon.device.messaging.permission.RECEIVE in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission com.htc.launcher.permission.READ_SETTINGS in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission com.htc.launcher.permission.UPDATE_SHORTCUT in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission com.huawei.android.launcher.permission.CHANGE_BADGE in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission com.sonyericsson.home.permission.BROADCAST_BADGE in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Unknown permission android.permission.UPDATE_APP_BADGE in package com.instagram.android

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.CALL_PHONE to package com.instagram.android because it was previously installed without

01-17 10:43:16.517   733   862 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package com.instagram.android because it was previously installed without

01-17 10:44:14.062   733   897 I ActivityManager: Start proc 4532:com.instagram.android/u0a95 for broadcast com.instagram.android/com.instagram.push.fbns.FbnsInitBroadcastReceiver

01-17 10:44:15.743   733  3845 I ActivityManager: Start proc 4604:com.instagram.android:mqtt/u0a95 for service com.instagram.android/com.facebook.rti.push.service.FbnsService

01-17 10:44:33.358   733  3841 I ActivityManager: Killing 4532:com.instagram.android/u0a95 (adj 904): empty #17

01-17 10:44:35.473   733  3841 I ActivityManager: Start proc 5868:com.instagram.android/u0a95 for broadcast com.instagram.android/com.instagram.dogfood.selfupdate.SelfUpdateUpgradeEventReceiver

01-17 10:44:58.980   733  6737 I ActivityManager: Killing 5868:com.instagram.android/u0a95 (adj 906): empty #17

01-17 10:45:13.668   733   794 I ActivityManager: Start proc 7178:com.instagram.android/u0a95 for broadcast com.instagram.android/com.instagram.notifications.push.FbnsPushNotificationHandler$IgFbnsCallbackReceiver

01-17 10:46:20.598   733  1161 I ActivityManager: Killing 7178:com.instagram.android/u0a95 (adj 904): empty #17

01-17 10:46:35.319   733   794 I ActivityManager: Start proc 8555:com.instagram.android/u0a95 for broadcast com.instagram.android/com.instagram.notifications.push.FbnsPushNotificationHandler$IgFbnsCallbackReceiver

01-17 10:51:13.185   935   935 W StatusBar: removeNotification for unknown key: 0|com.instagram.android|64278|iglive|315037465_live_broadcast|10095

01-17 10:54:56.823   733  1665 I ActivityManager: Process com.instagram.android (pid 8555) has died

01-17 10:55:29.897   733   794 I ActivityManager: Start proc 11496:com.instagram.android/u0a95 for broadcast com.instagram.android/com.instagram.notifications.push.FbnsPushNotificationHandler$IgFbnsCallbackReceiver

01-17 10:55:30.652 11496 11496 E b       : Starting ANR detector for process: com.instagram.android

01-17 10:55:31.109 11496 11532 I art     : Thread[17,tid=11532,Native,Thread*=0xde7d6f00,peer=0x12ea2700,"IgExecutor #5"] recursive attempt to load library "/data/app/com.instagram.android-1/lib/arm/libfb.so"

01-17 10:58:51.976   733  2871 I ActivityManager: Process com.instagram.android (pid 11496) has died

01-17 11:00:32.655   733   794 I ActivityManager: Start proc 12349:com.instagram.android/u0a95 for broadcast com.instagram.android/com.instagram.common.analytics.AnalyticsUploadAlarmReceiver

01-17 11:00:33.367 12349 12349 E b       : Starting ANR detector for process: com.instagram.android

01-17 11:00:33.806 12349 12380 I art     : Thread[16,tid=12380,Native,Thread*=0xde7d9a00,peer=0x12e89ee0,"IgExecutor #4"] recursive attempt to load library "/data/app/com.instagram.android-1/lib/arm/libfb.so"

01-17 11:02:29.715   733   858 I ActivityManager: Killing 12349:com.instagram.android/u0a95 (adj 906): empty #17

01-17 11:02:41.456   733  3846 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.instagram.android/.activity.MainTabActivity bnds=[27,273][232,565] (has extras)} from uid 10109 on display 0

01-17 11:02:41.688   733  3846 I ActivityManager: Start proc 13071:com.instagram.android/u0a95 for activity com.instagram.android/.activity.MainTabActivity

01-17 11:02:42.202 13071 13071 E b       : Starting ANR detector for process: com.instagram.android

01-17 11:02:42.439 13071 13102 I art     : Thread[17,tid=13102,Native,Thread*=0xde50a000,peer=0x12e9d550,"IgExecutor #5"] recursive attempt to load library "/data/app/com.instagram.android-1/lib/arm/libfb.so"

01-17 11:02:42.867 13096 13096 W com.instagram.android: type=1400 audit(0.0:9264): avc: denied { read } for uid=10095 comm=49674578656375746F72202331 name="xposed" dev="mmcblk0p25" ino=48260 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0

01-17 11:02:43.473   733   801 I ActivityManager: Displayed com.instagram.android/.activity.MainTabActivity: +1s834ms

01-17 11:02:43.849   733  3848 I ActivityManager: Start proc 13193:com.instagram.android:igplayer/u0a95 for service com.instagram.android/com.instagram.exoplayer.service.proxy.ExoPlayerServiceDextricksProxy

01-17 11:02:44.338 13193 13193 E b       : Skipping ANR Detector for process: com.instagram.android:igplayer

01-17 11:02:44.475 13193 13193 I art     : Thread[1,tid=13193,Native,Thread*=0xe8e05400,peer=0x73dda818,"main"] recursive attempt to load library "/data/app/com.instagram.android-1/lib/arm/libfb.so"

01-17 11:02:44.543 13096 13096 W com.instagram.android: type=1400 audit(0.0:9292): avc: denied { read } for uid=10095 comm=49674578656375746F72202331 name="xposed" dev="mmcblk0p25" ino=48260 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0

01-17 11:02:44.546 13142 13142 W com.instagram.android: type=1400 audit(0.0:9293): avc: denied { read } for uid=10095 comm=49674578656375746F72202337 name="xposed" dev="mmcblk0p25" ino=48260 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0

01-17 11:02:44.570 13096 13096 W com.instagram.android: type=1400 audit(0.0:9294): avc: denied { read } for uid=10095 comm=49674578656375746F72202331 name="xposed" dev="mmcblk0p25" ino=48260 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0

01-17 11:02:44.573 13142 13142 W com.instagram.android: type=1400 audit(0.0:9295): avc: denied { read } for uid=10095 comm=49674578656375746F72202337 name="xposed" dev="mmcblk0p25" ino=48260 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0

01-17 11:03:13.145   733   859 I InputDispatcher: Application is not responding: Window{c0b7fd2 u0 com.instagram.android/com.instagram.android.activity.MainTabActivity}.  It has been 5001.0ms since event, 5000.6ms since wait started.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 9.  Wait queue head age: 5565.2ms.

01-17 11:03:13.182   733   859 I WindowManager: Input event dispatching timed out sending to com.instagram.android/com.instagram.android.activity.MainTabActivity.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 9.  Wait queue head age: 5565.2ms.

01-17 11:03:16.358   733   794 E ActivityManager: ANR in com.instagram.android (com.instagram.android/.activity.MainTabActivity)

01-17 11:03:18.229   733   795 W ActivityManager:   Force finishing activity com.instagram.android/.activity.MainTabActivity

01-17 11:03:18.235   733   795 I ActivityManager: Killing 13071:com.instagram.android/u0a95 (adj 0): user request after error

01-17 11:03:18.347   733  4987 I WindowManager: WIN DEATH: Window{c0b7fd2 u0 com.instagram.android/com.instagram.android.activity.MainTabActivity}

01-17 11:03:18.348   733  4987 W WindowManager: Force-removing child win Window{51e5fbf u0 AtchDlg:com.instagram.android/com.instagram.android.activity.MainTabActivity} from container Window{c0b7fd2 u0 com.instagram.android/com.instagram.android.activity.MainTabActivity}

---- 17 gen 2018 12:04:19 ----

**Comment by Moyster** [comment]
01-17 11:02:44.543 13096 13096 W com.instagram.android: type=1400 audit(0.0:9292): avc: denied { read } for uid=10095 comm=49674578656375746F72202331 name="xposed" dev="mmcblk0p25" ino=48260 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=0

Follow the bug report instructions and do a clean install without the problematic mod(s) before reporting.
