### ISSUE TITLE
Instagram Crash

### ISSUE THREAD

**Issue by micheleberrettis1** [Moyster/nougat_device_meizu_m2note#71]
Instagram stories crash, clean installation of newer build.

---- 19 gen 2018 7:02:30 AM ----
--------- beginning of main
01-19 07:01:08.508 13741 13741 W System  : ClassLoader referenced unknown path: /data/app/scd.lcex-1/lib/arm64
01-19 07:01:08.810 13741 13741 I [MALI][Gralloc]: [+]r_hnd(0x76146bd6c0), client(37), share_fd(38)
01-19 07:01:08.851 13741 13741 W RenderThread: type=1400 audit(0.0:899): avc: denied { read } for uid=10116 name="dev_info" dev="sysfs" ino=7101 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_devinfo:s0 tclass=file permissive=0
01-19 07:01:08.851 13741 13741 W RenderThread: type=1400 audit(0.0:900): avc: denied { read } for uid=10116 name="dev_info" dev="sysfs" ino=7101 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs_devinfo:s0 tclass=file permissive=0
01-19 07:01:08.856 13741 13763 W [DRVB]  : sec_drv_base_check: DRVB PROCESS STATUS = 0x1004
01-19 07:01:08.856 13741 13763 W [DRVB]  : sec_drv_base_check: DRVB PROCESS STATUS = 0x1004
01-19 07:01:08.863 13741 13763 I OpenGLRenderer: Initialized EGL, version 1.4
01-19 07:01:08.946 13741 13763 I [MALI][Gralloc]: [+]r_hnd(0x761346f800), client(37), share_fd(47)
01-19 07:01:09.100 13741 13763 I [MALI][Gralloc]: [+]r_hnd(0x761357d900), client(37), share_fd(49)
01-19 07:01:09.140 13741 13763 I [MALI][Gralloc]: [+]r_hnd(0x761357e3a0), client(37), share_fd(48)
01-19 07:01:09.148 13741 13763 W MALI    : glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 11152
01-19 07:01:09.193 13741 13763 I [MALI][Gralloc]: [+]r_hnd(0x7613580a60), client(37), share_fd(51)
01-19 07:01:09.217 13741 13763 I [MALI][Gralloc]: [+]r_hnd(0x7612704780), client(37), share_fd(52)
01-19 07:01:09.232 13741 13763 I [MALI][Gralloc]: [+]r_hnd(0x7612705400), client(37), share_fd(53)
01-19 07:01:10.382 13741 13763 I [MALI][Gralloc]: [-]r_hnd(0x7612704780), client(37), share_fd(52)
01-19 07:01:10.385 13741 13763 I [MALI][Gralloc]: [-]r_hnd(0x761357d900), client(37), share_fd(49)
01-19 07:01:10.389 13741 13763 I [MALI][Gralloc]: [-]r_hnd(0x761346f800), client(37), share_fd(47)
01-19 07:01:10.577 13741 13747 I art     : Do partial code cache collection, code=21KB, data=30KB
01-19 07:01:10.578 13741 13747 I art     : After code cache collection, code=21KB, data=30KB
01-19 07:01:10.578 13741 13747 I art     : Increasing code cache capacity to 128KB
01-19 07:01:12.464 13741 13747 I art     : Do partial code cache collection, code=52KB, data=61KB
01-19 07:01:12.465 13741 13747 I art     : After code cache collection, code=52KB, data=61KB
01-19 07:01:12.465 13741 13747 I art     : Increasing code cache capacity to 256KB
01-19 07:01:19.840 13741 13818 W ResourceType: Failure getting entry for 0x7f030000 (t=2 e=0) (error -75)
01-19 07:01:19.840 13741 13818 W PackageManager: Failure retrieving resources for com.google.android.apps.turbo: Resource ID #0x7f030000
01-19 07:01:19.893 13741 13747 I art     : Do full code cache collection, code=124KB, data=123KB
01-19 07:01:19.903 13741 13747 I art     : Starting a blocking GC JitCodeCache
01-19 07:01:19.904 13741 13747 I art     : After code cache collection, code=102KB, data=89KB
01-19 07:01:20.600 13741 13747 I art     : Do partial code cache collection, code=123KB, data=115KB
01-19 07:01:20.601 13741 13747 I art     : After code cache collection, code=122KB, data=115KB
01-19 07:01:20.601 13741 13747 I art     : Increasing code cache capacity to 512KB
01-19 07:01:22.740 13741 13763 W MALI    : glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 6911
01-19 07:01:30.314 13741 13763 I [MALI][Gralloc]: [-]r_hnd(0x7612705400), client(37), share_fd(53)
01-19 07:01:30.326 13741 13763 I [MALI][Gralloc]: [-]r_hnd(0x7613580a60), client(37), share_fd(51)
01-19 07:01:30.335 13741 13763 I [MALI][Gralloc]: [-]r_hnd(0x761357e3a0), client(37), share_fd(48)
---- 19 gen 2018 7:02:30 AM ----

**Comment by Moyster** [comment]
January 2018 security bulletin made Mediatek's AVC decoder crash hard, there's a quick tip if you don't use "gallery app" to play self-recorded videos, just remove AVC decoder from the codecs_profile.xml, you can still record videos but can't read it (lack of Mtk decoder to read Mtk encoded videos (AVC encoder works properly, as far as I know).  
Should be fixed in next build, soon(tm)
