### ISSUE TITLE
Issues for Magisk v16.0 on build 21

### ISSUE THREAD

**Issue by zhou1012** [Moyster/nougat_device_meizu_m2note#74]
When I try to use sbin/su, the system always says `No such file or directory`

**Comment by micheleberrettis1** [comment]
This issue is for magisk 15.0+,
Flash 14.0, Grant the root to the apps and then flash 16 or keep 14.

**Comment by micheleberrettis1** [comment]
This issue is for magisk 15.0+,
Flash 14.0, Grant the root to the apps and then flash 16 or keep 14.

**Comment by hawkeye116477** [comment]
On my Shield Tablet, Magisk 16 works, so why it doesn't work on Meizu M2 Note?
