### ISSUE TITLE
Data not counting

### ISSUE THREAD

**Issue by eduardo579** [Moyster/nougat_device_meizu_m2note#8]
The data usage is frozen at 0 kb. Some of us have already reported this issue on XDA.

**Comment by Moyster** [comment]
Yep, seems like netd needs some fixes, it's not crucial but still nice to have ;)

**Comment by Moyster** [comment]
Data counting is fixed and will be included in next release ;)

**Comment by mohancm100** [comment]
@Moyster how did you fixed data count?
