### ISSUE TITLE
ReBuilding build 21.xx

### ISSUE THREAD

**Issue by SeaPlayerPotato** [Moyster/nougat_device_meizu_m2note#84]
Hi moyster , i already used meizu m2 note really long time ,but i just found about cusrom like some week ago , i been try u build 21 (dec 2017 ?) it been recommend over and over on xda forum, yeah it really good but i can't make my sdcard to be internal memory , then i trying build 24 it work for make my sdcard to be internal memory , but the devices got reboot after some hour i used this build , i just want request can you rebuild build 21 , just fixed the feature for make sdcard can be internal memory ? (i already tried old poet from user recommend for try use this feature in latest build then downgrade, but it not work for me , when i back to build 21 it's ask to format sdcard)

sorry for my bad english, anyway thanks for u hardwork to this build , u really helping my phone to be feel good once more

**Comment by Moyster** [comment]
A bit late to the party but here we go :  
https://drive.google.com/open?id=1hCoUdvpPs8w-VOVIzdhsB2SfkK7wz4C5  

Sdcard as internal memory shouldn't crash if you move apps to it, (also in the new build ; a lot of stability improvement, orientation sensor doesn't stop working after a week/10 days without reboot anymore, latest September '19 Android Security Bulletin)  

Hf
